"""Appendix B diagnostic thresholds."""

CRISIS_CORRELATION_THRESHOLD = 0.85
MIN_FILL_RATIO_EXECUTION = 0.90
MIN_FILL_RATIO_LIQUIDITY = 0.80
PROJECTED_IC_FLOOR = 0.02
RESILIENCE_UNHEALTHY_LEVELS = frozenset({"safe", "halt", "critical"})
INTERVENTION_LOOKBACK_DAYS = 7
DATA_VALIDATION_SYMBOL_LIMIT = 3
